Hw04 auth
kglanos/goit-node-hw-02 pull request #3
Opened 2024-02-18 22:43 UTC by kglanos

Cześć,
Zostały wykonane wszystkie kroki, sprawdzone zostały poprawność działania, problem mam z autoryzacją na którą dostaje błąd. Prośba o review i komentarz co poprawić. Z góry dziękuje.

2024-02-19 20:24 UTC, KamilMr requested changes
Komentarze w kodzie i na slaku

2024-02-19 20:24 UTC, KamilMr commented on routes/api/users.js
> +    }
Myślę że to jest nie potrzebne? Bo co tutaj sprawdzasz jeszcze? signupAndLoginValidation sprawdzasz dane przyjciowe, a to?

2024-02-19 20:24 UTC, KamilMr commented on services/usersService.js
> +const login = async (email) => {
Ta nazwa jest myląca, pownna być `getUserByEmail`

2024-02-19 20:24 UTC, KamilMr commented on routes/api/users.js
> +        let user = await login(email);
```suggestion
        let user = await getUserByEmail(email);
```

2024-02-19 20:24 UTC, KamilMr commented on routes/api/users.js
> +        const user = await User.findById(userId);
moze użyj find and update? Poszukaj metody która znajduje i robi update, czyli ustawia token jako pusty. Zmniejszysz ilość kodu. I sprawdź co otrzymujesz, w zależności od odpowiedzi zwróc odpowiedni komunikat o błędzie lub sukcesie

2024-02-19 20:24 UTC, KamilMr commented on routes/api/users.js
> +        }
Tego nie potrzebujesz ponieważ verifyToken na to nie pozwoli, jeśli coś nie tak z tokenem użytkownika to komunikat zostanie przerwany przed tym miejscem, w verifyToken

2024-02-19 20:24 UTC, KamilMr requested changes

2024-02-19 20:24 UTC, KamilMr commented on middlewares/auth.js
> +module.exports = verifyToken;
```suggestion
const jwt = require("jsonwebtoken");
const { User } = require("../services/schemas/userSchema"); // fix import this is default
require("dotenv").config();

const verifyToken = async (req, res, next) => {
    try {
        const authHeader = req.headers.authorization;

        if (!authHeader || !authHeader.startsWith("Bearer ")) {
        return res.status(401).json({ message: "Not authorized" }); // change message 
        }

        const token = authHeader.split(" ")[1];

        const verify = jwt.verify(token, process.env.JWT_SECRET);
        console.log(verify); // verify.user.id
        const user = await User.findOne({ _id: verify.id });

        if (!user || user.token !== token) {
        return res.status(401).json({ message: "Not authorized" });
        }
        req.user = user;
        next();
        } catch (error) {
            console.log(error); // always console log error 
        return res.status(401).json({ message: "Not authorized" }); // change massage
    }
};

module.exports = verifyToken;

```

2024-02-19 23:50 UTC, kglanos commented
Cześć, poprawki zostały wykonane. Kod został przetestowany w postman i uzyskuje wszystkie odpowiedzi.

2024-02-20 20:36 UTC, KamilMr approved these changes
Nice changes 🎉

2024-02-22 19:23 UTC, merged